# Generated by Django 3.0.4 on 2020-03-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200305_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.CreateModel(
            name='Lesson_to_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Instructor')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Lesson')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Student')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(through='api.Lesson_to_Person', to='api.Student'),
        ),
    ]
