# Generated by Django 3.0.4 on 2020-03-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200309_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='instructor',
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructor',
            field=models.ManyToManyField(through='api.Lesson_to_Person', to='api.Instructor'),
        ),
    ]
